export const TokenType = {
  LEFT_PAREN: "(",
  RIGHT_PAREN: ")",
  LEFT_BRACKET: "[",
  RIGHT_BRACKET: "]",
  LEFT_BRACE: "{",
  RIGHT_BRACE: "}",
  COMMA: ",",
  COLON: ":",
  SEMICOLON: ";",
  ARROW: "=>",
  POINT: ".",
  ASTERISK: "*",
  SLASH: "/",
  PERCENT: "%",
  PLUS: "+",
  MINUS: "-",
  BANG: "!",
  LT: "<",
  GT: ">",
  LTE: "<=",
  GTE: ">=",
  EQEQ: "==",
  EQEQEQ: "===",
  NOTEQ: "!=",
  NOTEQEQ: "!==",
  AND: "&&",
  OR: "||",
  NULLISH: "??",
  QUESTION: "?",
  OPTIONAL_CHAIN: "?.",
  IDENTIFIER: "<identifier>",
  BOOLEAN: "<boolean>",
  FLOAT: "<float>",
  INTEGER: "<integer>",
  NULL: "<null>",
  STRING: "<string>",
  TEMPLATE: "<template>",
} as const;

export type TokenTypeValue = (typeof TokenType)[keyof typeof TokenType];
